# Generated by Django 5.2.4 on 2025-07-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_course_stripe_price_id_course_stripe_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
